

class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationsArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...


